Update blank.yml (#2)
* Update blank.yml

* Update blank.yml

* Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -5,8 +5,8 @@ name: CI
 # Controls when the workflow will run
 on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
+  #push:
+  #  branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
 
@@ -34,3 +34,12 @@ jobs:
         run: |
           echo Add other actions to build,
           echo test, and deploy your project.
+  #job_2:
+  #  runs-on: ubuntu-latest
+ #   steps:
+  #    - name: Run script
+    #    run: echo Hellow from Job 2!
+
+  #    - name: Fail script
+  #      run: exit 1
+        
